version: 1
services:
  - type: web
    name: my-chatbot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: FLASK_ENV
        value: development
